Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/data/*'
    - 'db/schema.rb'
    - 'db/data_schema.rb'
    - 'bin/bundle'
    - 'config/routes.rb'
  NewCops: enable
